### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by m1guelpf** [euautomation/graphql-client#4]
Could you share a simple  example on how to use it?
There aren't any docs... 😢

**Comment by mnpenner** [comment]
+1 a usage example or two in the README would be appreciated :smile:

**Comment by fragglebob** [comment]
Sounds like good idea tbh. We'll get a few examples together.

**Comment by eNzyOfficial** [comment]
Done! :1st_place_medal:

**Comment by mnpenner** [comment]
Looks good, thank you!
