### ISSUE TITLE
GraphQL mutations

### ISSUE THREAD

**Issue by RavivCohen-BWEBI** [euautomation/graphql-client#5]
How do you handle mutations?
Do you have a full sample code?

Thanks

**Comment by eNzyOfficial** [comment]
https://github.com/euautomation/graphql-client#other-responses

See above, pass in your mutation query and recieve the response as a raw guzzle response or json, depending on what you're after.

```
$client = new Client();
$client->setUrl($graphQLURL);

$query = "Your mutation query goes here...";
$variables = ["Your mutation vars go here"];
$headers = ["Your headers"];

$response = $client->json($query, $variables, $headers);
```

$vars and $headers are optional :+1:

**Comment by RavivCohen-BWEBI** [comment]
That is exactly what i have tried and i get an error response.

Sample query:
```
$data ='{
            "query":
            "mutation {createPlans (name: \"aa\" description: \"aa\" price: 10 categoryId: 2 billingCycleId: 2 levelTypeId: 2 ){ id } }"
        }';
```

Posting the data:
```
$client = new GraphQLClient($end_point);
$response = $client->json($data);
```

Response:
(1/1) GraphQLMissingData
There was an error with the GraphQL response, no data key was found.

Note:
The process as is works when i instantiated a Guzzle client directly in my code and posted the same query for the same end point.
But i wanted a dedicated package to work with and your solution looks good,
just need some more specifications and help with the error received.

**Comment by eNzyOfficial** [comment]
Can you paste what is being returned from the guzzle client when it works?
